# Generated by Django 5.1.4 on 2025-04-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500, null=True)),
                ('upi_id', models.CharField(default='', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotel_logo_images/')),
                ('mobile', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('gst_status', models.IntegerField(default=0)),
                ('gst_number', models.CharField(max_length=200, null=True)),
                ('discount_status', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sunil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('bills', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('mobile', models.IntegerField(null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.hotel')),
            ],
        ),
    ]
