# Generated by Django 5.1.4 on 2025-03-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_payment',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
