# Generated by Django 5.1.4 on 2025-03-01 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.table')),
            ],
        ),
    ]
