# Generated by Django 5.1.4 on 2025-03-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_qrcode',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
