# Generated by Django 5.1.4 on 2025-03-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_item_image_and_youtube_url'),
        ('table_qr', '0002_alter_table_qrcode_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField(default=0)),
                ('qty', models.IntegerField()),
                ('note', models.CharField(max_length=100, null=True)),
                ('accepted_status', models.CharField(default='Pendding', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.item')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.table')),
            ],
        ),
    ]
