# Generated by Django 5.1.4 on 2025-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_qr', '0003_customer_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_cart',
            name='customer_session_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
