# Generated by Django 5.1.4 on 2025-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_qr', '0004_customer_cart_customer_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_qrcode',
            name='session_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
