# Generated by Django 5.1.4 on 2025-04-10 08:58

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('order_by', models.IntegerField(default=1)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathi_name', models.CharField(max_length=100, null=True)),
                ('english_name', models.CharField(max_length=100, null=True)),
                ('gst_status', models.IntegerField(default=0)),
                ('discount_status', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('status', models.IntegerField(default=1)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Item_image_and_youtube_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', embed_video.fields.EmbedVideoField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.item')),
            ],
        ),
        migrations.CreateModel(
            name='order_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('s_gst', models.FloatField(default=0, null=True)),
                ('c_gst', models.FloatField(default=0, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('discount_amount', models.FloatField(default=0, null=True)),
                ('cash_amount', models.FloatField(default=0, null=True)),
                ('phone_pe_amount', models.FloatField(default=0, null=True)),
                ('pos_machine_amount', models.FloatField(default=0, null=True)),
                ('paid_status', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0, null=True)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.item')),
                ('order_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.order_master')),
            ],
        ),
        migrations.CreateModel(
            name='selected_item_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.category')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.item')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='order_master',
            name='table',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.table'),
        ),
        migrations.CreateModel(
            name='Hotel_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField(default=0)),
                ('qty', models.IntegerField()),
                ('note', models.CharField(max_length=100, null=True)),
                ('cook_status', models.CharField(default='Pendding', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('chef_id', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(max_length=500, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.employee')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.hotel')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.item')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.table')),
            ],
        ),
    ]
