# Generated by Django 5.1.4 on 2025-03-02 05:32

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_image_and_youtube_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', embed_video.fields.EmbedVideoField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.item')),
            ],
        ),
    ]
