# Generated by Django 5.1.4 on 2025-03-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_item_image_and_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_cart',
            name='chef_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel_cart',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.employee'),
        ),
    ]
