# Generated by Django 5.1.4 on 2025-03-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_cart_chef_id_hotel_cart_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_cart',
            name='session_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
